name: AussieAusborne
favicon: null
layout_spectrum: 0.04241455998271704
typography_spectrum: 0.5764431324787438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0675370420794934
  lightness: 0.8218677185941488
  saturation: 0.039661678951233625
  rhythmicContrast: 0.2525102796498686
purpose: []
